---
- name: Create RKE2 artifact directory on bastion
  file:
    path: /tmp/rke2-artifacts
    state: directory
    mode: '0755'
  become: true

- name: Download RKE2 files on bastion
  block:
    - name: Download install script
      get_url:
        url: https://raw.githubusercontent.com/rancher/rke2/master/install.sh
        dest: /tmp/rke2-install.sh
        mode: '0755'
        timeout: 60
        headers:
          Accept: application/octet-stream
      register: download_result
      until: download_result is success
      retries: 3
      delay: 5
      become: true

    - name: Download checksum file
      get_url:
        url: "https://github.com/rancher/rke2/releases/download/{{ rke2_version | default('v1.24.1+rke2r1') }}/sha256sum-amd64.txt"
        dest: /tmp/rke2-artifacts/sha256sum-amd64.txt
        mode: '0644'
        timeout: 60
        headers:
          Accept: application/octet-stream
      register: download_result
      until: download_result is success
      retries: 3
      delay: 5
      become: true

    - name: Download RKE2 binary
      get_url:
        url: "https://github.com/rancher/rke2/releases/download/{{ rke2_version | default('v1.24.1+rke2r1') }}/rke2.linux-amd64"
        dest: /tmp/rke2-artifacts/rke2
        mode: '0755'
        timeout: 60
        headers:
          Accept: application/octet-stream
      register: download_result
      until: download_result is success
      retries: 3
      delay: 5
      become: true

    - name: Download RKE2 images
      get_url:
        url: "https://github.com/rancher/rke2/releases/download/{{ rke2_version | default('v1.24.1+rke2r1') }}/rke2-images.linux-amd64.tar.gz"
        dest: /tmp/rke2-artifacts/rke2-images.tar.gz
        mode: '0644'
        timeout: 60
        headers:
          Accept: application/octet-stream
      register: download_result
      until: download_result is success
      retries: 3
      delay: 5
      become: true

    - name: Verify downloaded files
      stat:
        path: "{{ item }}"
      register: file_check
      failed_when: not file_check.stat.exists
      loop:
        - /tmp/rke2-install.sh
        - /tmp/rke2-artifacts/sha256sum-amd64.txt
        - /tmp/rke2-artifacts/rke2
        - /tmp/rke2-artifacts/rke2-images.tar.gz

- name: Create shared directory for RKE2 files
  file:
    path: /opt/rke2-files
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true

- name: Create staging directory structure
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop:
    - /tmp/rke2-bundle-staging/tmp
    - /tmp/rke2-bundle-staging/tmp/rke2-artifacts
  become: true

- name: Copy files to staging directory
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: preserve
    remote_src: true
  loop:
    - { src: "/tmp/rke2-install.sh", dest: "/tmp/rke2-bundle-staging/tmp/rke2-install.sh" }
    - { src: "/tmp/rke2-artifacts/rke2", dest: "/tmp/rke2-bundle-staging/tmp/rke2-artifacts/rke2" }
    - { src: "/tmp/rke2-artifacts/rke2-images.tar.gz", dest: "/tmp/rke2-bundle-staging/tmp/rke2-artifacts/rke2-images.tar.gz" }
    - { src: "/tmp/rke2-artifacts/sha256sum-amd64.txt", dest: "/tmp/rke2-bundle-staging/tmp/rke2-artifacts/sha256sum-amd64.txt" }

- name: Create archive of RKE2 files
  archive:
    path: "/tmp/rke2-bundle-staging/tmp"
    dest: /opt/rke2-files/rke2-bundle.tar.gz
    format: gz
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
    remove: true
  become: true

- name: Display bundle contents
  command: tar tvf /opt/rke2-files/rke2-bundle.tar.gz
  register: bundle_contents
  changed_when: false

- name: Show bundle structure
  debug:
    msg: "Bundle contents:\n{{ bundle_contents.stdout_lines | join('\n') }}"

- name: Clean up staging directory
  file:
    path: /tmp/rke2-bundle-staging
    state: absent
  become: true

- name: Verify archive contents
  command: tar tvf /opt/rke2-files/rke2-bundle.tar.gz
  register: archive_contents
  changed_when: false

- name: Verify bundle creation
  stat:
    path: /opt/rke2-files/rke2-bundle.tar.gz
  register: bundle_check
  failed_when: not bundle_check.stat.exists

- name: Report bundle status
  debug:
    msg: |
      RKE2 Bundle Status:
      - Location: /opt/rke2-files/rke2-bundle.tar.gz
      - Size: {{ bundle_check.stat.size | default('N/A') }}
      - Owner: {{ bundle_check.stat.pw_name | default('N/A') }}
      - Permissions: {{ bundle_check.stat.mode | default('N/A') }}
