---
# K3s Installation Role Defaults

# K3s version and installation settings
kubernetes_version: "{{ kubernetes_version | default('v1.28.15+k3s1') }}"
k3s_channel: "{{ channel | default('') }}"

# K3s configuration
k3s_node_type: server  # Options: cluster-init, server, agent
k3s_token: "{{ node_token | default('') }}"
k3s_node_roles: "{{ node_role | default('etcd,cp,worker') }}"

# Network configuration  
kube_api_host: "{{ kube_api_host }}"
fqdn: "{{ fqdn | default('') }}"
public_ip: "{{ public_ip | default('') }}"

# Additional configuration flags
server_flags: "{{ server_flags | default('') }}"
worker_flags: "{{ worker_flags | default('') }}"

# Security hardening
k3s_security_hardening: false
k3s_cis_config: "{{ cis_master_config_yaml_content | default('') }}"

# Service management
k3s_service_state: started
k3s_service_enabled: true

# Installation validation
k3s_validate_certs: true
