---
- name: Fix RKE2 Configuration and Restart Service
  hosts: airgap_nodes
  become: true
  gather_facts: true
  tasks:
    - name: Stop RKE2 server service
      systemd:
        name: rke2-server
        state: stopped
      ignore_errors: yes

    - name: Remove old RKE2 configuration
      file:
        path: /etc/rancher/rke2/config.yaml
        state: absent

    - name: Regenerate RKE2 server configuration
      template:
        src: roles/rke2_install/templates/config.yaml.j2
        dest: /etc/rancher/rke2/config.yaml
        owner: root
        group: root
        mode: '0644'
      when: inventory_hostname == groups['airgap_nodes'][0]

    - name: Regenerate RKE2 agent configuration for additional nodes
      template:
        src: roles/rke2_install/templates/agent-config.yaml.j2
        dest: /etc/rancher/rke2/config.yaml
        owner: root
        group: root
        mode: '0644'
      when: inventory_hostname != groups['airgap_nodes'][0]

    - name: Display new RKE2 configuration
      command: cat /etc/rancher/rke2/config.yaml
      register: new_config

    - name: Show new configuration
      debug:
        msg: |
          New RKE2 Configuration:
          {{ new_config.stdout }}

    - name: Start RKE2 server service
      systemd:
        name: rke2-server
        state: started
        enabled: yes
      when: inventory_hostname == groups['airgap_nodes'][0]

    - name: Wait for RKE2 server to be ready
      wait_for:
        path: /var/lib/rancher/rke2/server/token
        timeout: 300
      when: inventory_hostname == groups['airgap_nodes'][0]

    - name: Get server token for agent nodes
      slurp:
        src: /var/lib/rancher/rke2/server/token
      register: server_token
      when: inventory_hostname == groups['airgap_nodes'][0]

    - name: Set server token fact
      set_fact:
        rke2_token: "{{ hostvars[groups['airgap_nodes'][0]]['server_token']['content'] | b64decode | trim }}"
      when: inventory_hostname != groups['airgap_nodes'][0]

    - name: Update agent configuration with server token
      template:
        src: roles/rke2_install/templates/agent-config.yaml.j2
        dest: /etc/rancher/rke2/config.yaml
        owner: root
        group: root
        mode: '0644'
      when: inventory_hostname != groups['airgap_nodes'][0]

    - name: Start RKE2 agent service on additional nodes
      systemd:
        name: rke2-agent
        state: started
        enabled: yes
      when: inventory_hostname != groups['airgap_nodes'][0]

    - name: Check RKE2 service status
      systemd:
        name: "{{ 'rke2-server' if inventory_hostname == groups['airgap_nodes'][0] else 'rke2-agent' }}"
      register: rke2_status

    - name: Display RKE2 service status
      debug:
        msg: |
          RKE2 Service Status:
          Name: {{ rke2_status.name }}
          State: {{ rke2_status.status.ActiveState }}
          Enabled: {{ rke2_status.status.UnitFileState }}