---
- name: Test SSH connectivity from local machine to bastion
  hosts: bastion
  gather_facts: false
  tasks:
    - name: Test bastion connectivity
      ansible.builtin.ping:

- name: Test SSH connectivity from local machine to airgap nodes via proxy
  hosts: airgap_nodes
  gather_facts: false
  tasks:
    - name: Test airgap node connectivity via proxy
      ansible.builtin.ping:

- name: Test direct connectivity from bastion to airgap nodes
  hosts: bastion
  gather_facts: false
  tasks:
    - name: Test direct SSH to airgap nodes from bastion
      ansible.builtin.shell: |
        ssh -o BatchMode=yes \
            -o ConnectTimeout=5 \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            -i {{ ssh_private_key_file }} \
            ubuntu@{{ hostvars[item]['ansible_host'] }} \
            'echo "Connection to {{ item }} successful"'
      loop: "{{ groups['airgap_nodes'] }}"
      register: direct_ssh_test
      changed_when: false

    - name: Display direct SSH test results
      ansible.builtin.debug:
        msg: "{{ direct_ssh_test.results }}"
