---
# K3s Installation Role - Handlers

- name: restart k3s
  systemd:
    name: k3s
    state: restarted
    daemon_reload: yes
  listen: restart k3s

- name: restart k3s-agent
  systemd:
    name: k3s-agent
    state: restarted
    daemon_reload: yes
  listen: restart k3s-agent
